name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use Google Cloud authentication
      run: |
        gcloud auth configure-docker europe-central2-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build \
          --build-arg EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
          --build-arg EMAIL_SENDER=${{ secrets.EMAIL_SENDER }} \
          --build-arg EMAIL_REC=${{ secrets.EMAIL_REC }} \
          -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/email-sender/python-app:latest .
        docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/email-sender/python-app:latest

    - name: Set up kubectl
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
        location: ${{ secrets.GKE_CLUSTER_LOCATION }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
